### ISSUE TITLE
Installations-instruktioner

### ISSUE THREAD

**Issue by ChristofferGoude** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#1]
Vissa delar av installations-instruktionerna skulle kunna utökas för att tillgodoseanvändare på andra operativsystem.

**Comment by OskarKlintrot** [comment]
Vad saknar du? Vagrant fungerar ju likadant för alla OS?

**Comment by OskarKlintrot** [comment]
Eftersom ingen ytterligare kommentar kommit in och issuen inte rör projektet stänger jag den.
