### ISSUE TITLE
Fel auth-token error

### ISSUE THREAD

**Issue by stoffesvensson** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#13]
Om man manipulerar Auth-token och skall använda en av CRUD funktionerna så "kraschar" sidan och visar det där härliga röda felmeddelandet om Rails tycker om att visa om man inte fångar ett fel. Skulle vara bra om man kunde fånga upp det och visa ett tydligt felmeddelande för användare att auth-token är fel.

**Comment by OskarKlintrot** [comment]
Hur tänker du nu egentligen? API:et konsumeras ju inte av en människa utan en maskin? Det viktiga är ju att felkoderna stämmer, till exempel att API:et svarar med en 401:a.
