### ISSUE TITLE
Summering

### ISSUE THREAD

**Issue by stoffesvensson** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#14]
Förutom issue som jag skrev innan fungerar APIet bra. Alla krav är fyllda och jag kan inte hitta något större fel. Bra instruktion om hur man får igång vagrant och hur man får igång postman filerna. Mycket bra jobb!!

**Comment by OskarKlintrot** [comment]
Bra att instruktionerna fungerade!
