### ISSUE TITLE
Unmet dependency when starting the Angular node.js server

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#16]
In the `.\angularApp\server` folder when running `npm install` and after that starting the server with `npm run dev`, it complains about not finding the `nodemon` command. It could be a local issue with my enviroment. I've got the latest version of `node.js` and and `npm` running windows 7.

I resolved the issue by running the command: `npm install nodemon --save`. You could add nodemon to package.json to always assure that it is available if you wish.

**Comment by OskarKlintrot** [comment]
Sorry, it's mentioned [here](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/README.md#setup) but I forgot to add it to the info for running the build. For some reason the build is not working (when I build the project I get an error that I don't get when running the dev code, I can't find the error) so the very last thing I did where to change the instruction to run the dev code and not the build. However I failed to update the instructions accordingly.
