### ISSUE TITLE
Suggestion: grunt serve instead of separate node server?

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#17]
Im sure you have a good reasong for it, which I am yet to discover. But a suggestion is that you could have just gone with running `grunt serve` as declared [here](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/angularApp/client/Gruntfile.js#L430) as your webserver for development instead of running a separate node server. 
The setup process would have been easier for a developer like me :-) But I am sure you had one or several good reasons for doing it this way.

**Comment by OskarKlintrot** [comment]
Deep linking ;)
