### ISSUE TITLE
Your app is like a fresh breeze in a jungle filled with angry boring gorillas without bananas

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#18]
I have to say, The user experience in your app made me smile. And that is the most importand thing that a javascript app should do: Make people smile. :+1:

Did not know about [this](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/angularApp/client/app/scripts/app.js#L71-L72). Just learned something new. Cool stuff :-)

**Comment by OskarKlintrot** [comment]
I really love the title! The other day I was able to write the issue "Okända apor kraschar servern" on a project I'm working at at work :monkey_face:
