### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by ChristofferGoude** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#2]
Det verkar för närvarande inte finnas någon administrationssida.

**Comment by OskarKlintrot** [comment]
Från https://coursepress.lnu.se/kurs/webbramverk/registreringsapplikation:

> - Möjlighet att logga in med adminstratörsrättigheter
> - En sida där den inloggade administratören kan ta bort(revoke) befintliga applikationer

Loggar du in som admin så ser du både dina egna nycklar samt alla andras nycklar:
![image](https://cloud.githubusercontent.com/assets/6783879/12959359/5d16e8ba-d036-11e5-9f7f-cf70b2daf1df.png)
