### ISSUE TITLE
Creating new op with existing tag name does not work.

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#21]
When creating a new `op` with an existing tag name, a 400 response is returned to the browser from the REST API but no info is given to the end user through the browser. I guess the desirable solution would be to either output an error message to the client or add the existing tag to the new `op` server side.

**Comment by OskarKlintrot** [comment]
I have totally missed that! Thanks for pointing it out!
