### ISSUE TITLE
The Pagination / Limit buttons do not seem to work

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#22]
I've created 12 `op`s with unique tag-names and trying to switch between all the `10, 25, 50, 100` buttons in the `search`  and the `tags` views. Nothing really happens. I suggest to either remove theese buttons or making the buttons work :100:

**Comment by OskarKlintrot** [comment]
I must have missed something when implementing the lib I have been using!
