### ISSUE TITLE
Allmänna tankar

### ISSUE THREAD

**Issue by ChristofferGoude** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#3]
Hade problem att testa applikationen då jag inte fick Vagrant att fungera mot filerna från repo't. Allt verkar okej härifrån men kan vara ett lokalt problem hos mig.

I övrigt verkar applikationen välgjord, användarna är skyddade korrekt, routingen ser bra ut, och låter användare registrera applikationer varpå en api-nyckel tilldelas.

**Comment by OskarKlintrot** [comment]
Vad fick du för problem rent konkret?

**Comment by OskarKlintrot** [comment]
Eftersom ingen ytterligare kommentar kommit in och issuen inte rör projektet stänger jag den.
