### ISSUE TITLE
Peer review hg222dv

### ISSUE THREAD

**Issue by henceee** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#4]
En inloggad utvecklare ska kunna registrera en eller flera applikationer och därmed få tillgång till en eller flera API-nycklar
Fungerade väl, snyggt interface. En icke inloggad användare kan ej komma åt keys heller, vilket är bra att en auktorisering görs. Admin hanteras som en ”vanlig” användare och har egna keys och dessutom samtliga keys. Vet inte om det var tänkt att admin skulle ha egna keys, men hur som helst finns revoke funktionaliteten.

Hade lite problem med installation, detta var innan issue fanns för detta. Jag valde att släppa detta och slänga in projektet i c9 istället, för att snabbt komma igång.   Då jag försökte köra vagrant up fick jag fölande fel:

The guest machine entered an invalid state while waiting for it
to boot [..] The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue
Då jag försökte updatera guest  VboxGuestAdditions:
ln: failed to create symbolic link ‘/usr/lib/VBoxGuestAdditions’: No such file or directory

I övrigt snyggt interface, all funktionalitet på plats, känns väl genomarbetat och upfyller samtliga krav. Ber om ursäkt för sen review, gjorde en förra veckan (10/2), men fyllde visst bara i formuläret.  Notera att du får dubbla reviews pga att det blev lite strul och det inte fanns någon utan tilldelad peer.

**Comment by OskarKlintrot** [comment]
> En inloggad utvecklare ska kunna registrera en eller flera applikationer och därmed få tillgång till en eller flera API-nycklar
> Fungerade väl, snyggt interface. En icke inloggad användare kan ej komma åt keys heller, vilket är bra att en auktorisering görs. Admin hanteras som en ”vanlig” användare och har egna keys och dessutom samtliga keys. Vet inte om det var tänkt att admin skulle ha egna keys, men hur som helst finns revoke funktionaliteten.

Nej, jag blev också lite osäker på huruvida admin skulle kunna ha egna nycklar eller inte men jag lät admin ha det ändå. Är ju inga stora ingrepp i koden för att checka så att användaren inte är admin innan man sparar nyckeln, om man vill ändra det längre fram.

> Hade lite problem med installation, detta var innan issue fanns för detta. Jag valde att släppa detta och slänga in projektet i c9 istället, för att snabbt komma igång. Då jag försökte köra vagrant up fick jag fölande fel:
> 
> ```
> The guest machine entered an invalid state while waiting for it
> to boot [..] The primary issue for this error is that the provider you're using
> is not properly configured. This is very rarely a Vagrant issue
> Då jag försökte updatera guest VboxGuestAdditions:
> ln: failed to create symbolic link ‘/usr/lib/VBoxGuestAdditions’: No such file or directory
> ```

Som det stod i felmeddelandet; `This is very rarely a Vagrant issue`. Öppna vbox och tvångsstäng boxen och försök igen så brukar det alltid lösa sig. Det är som sagt inte ett fel med den vagrant filen som ligger här. Jag vet inte vad #1 syftar till eftersom det inte finns några kommentarer. 

> I övrigt snyggt interface, all funktionalitet på plats, känns väl genomarbetat och upfyller samtliga krav. Ber om ursäkt för sen review, gjorde en förra veckan (10/2), men fyllde visst bara i formuläret. Notera att du får dubbla reviews pga att det blev lite strul och det inte fanns någon utan tilldelad peer.

Alltid kul med feedback :smile: Tänk dock på att gärna dela upp feedbacken i flera mindre issues så man kan stänga dem efterhand. I det här fallet gjorde det dock inget eftersom jag kan stänga denna issue direkt.
